services:
  portfolio:
    image: portfolio:latest
    container_name: portfolio
    restart: unless-stopped
    networks:
      - portfolio-network
      - dokploy-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.portfolio-web.rule=Host(`portfolio-85-215-218-163.traefik.me`)
      - traefik.http.routers.portfolio-web.entrypoints=web
      - traefik.http.routers.portfolio-web.middlewares=redirect-to-https@file
      - traefik.http.routers.portfolio-web.service=portfolio-web
      - traefik.http.routers.portfolio-websecure.rule=Host(`portfolio-85-215-218-163.traefik.me`)
      - traefik.http.routers.portfolio-websecure.entrypoints=websecure
      - traefik.http.routers.portfolio-websecure.tls.certresolver=letsencrypt
      - traefik.http.routers.portfolio-websecure.service=portfolio-websecure
      - traefik.http.services.portfolio-web.loadbalancer.server.port=3000
      - traefik.http.services.portfolio-websecure.loadbalancer.server.port=3000

networks:
  portfolio-network:
    name: portfolio-network
  dokploy-network:
    name: dokploy-network
    external: true
