import type { MediaItem } from '../components/Gallery';

// Erzeugt von scratchpad/galerie.py. Nicht von Hand aendern, sonst
// ist es beim naechsten Lauf wieder weg.
export const galleries: Record<string, MediaItem[]> = {
  "Hardware from scratch": [
    { src: "/gallery/hardware-from-scratch/aufbau-am-steckbrett-mit-schrittmotor.jpg", thumb: "/gallery/hardware-from-scratch/aufbau-am-steckbrett-mit-schrittmotor_t.jpg", type: "image" },
    { src: "/gallery/hardware-from-scratch/aufbau-am-steckbrett.mp4", thumb: "/gallery/hardware-from-scratch/aufbau-am-steckbrett_t.jpg", type: "video" },
    { src: "/gallery/hardware-from-scratch/cad-fertigungslinie.jpg", thumb: "/gallery/hardware-from-scratch/cad-fertigungslinie_t.jpg", type: "image" },
    { src: "/gallery/hardware-from-scratch/dobot-magician-greifen.mp4", thumb: "/gallery/hardware-from-scratch/dobot-magician-greifen_t.jpg", type: "video" },
    { src: "/gallery/hardware-from-scratch/drehbank-metallteile.mp4", thumb: "/gallery/hardware-from-scratch/drehbank-metallteile_t.jpg", type: "video" },
    { src: "/gallery/hardware-from-scratch/fraesen-aluminium.mp4", thumb: "/gallery/hardware-from-scratch/fraesen-aluminium_t.jpg", type: "video" },
    { src: "/gallery/hardware-from-scratch/gefraestes-blechteil.mp4", thumb: "/gallery/hardware-from-scratch/gefraestes-blechteil_t.jpg", type: "video" },
    { src: "/gallery/hardware-from-scratch/linienfolger-eigene-platine-01.mp4", thumb: "/gallery/hardware-from-scratch/linienfolger-eigene-platine-01_t.jpg", type: "video" },
    { src: "/gallery/hardware-from-scratch/linienfolger-eigene-platine-02.mp4", thumb: "/gallery/hardware-from-scratch/linienfolger-eigene-platine-02_t.jpg", type: "video" },
    { src: "/gallery/hardware-from-scratch/lochrasterplatine-handverdrahtet.jpg", thumb: "/gallery/hardware-from-scratch/lochrasterplatine-handverdrahtet_t.jpg", type: "image" },
    { src: "/gallery/hardware-from-scratch/platine-fertig-bestueckt-2021.jpg", thumb: "/gallery/hardware-from-scratch/platine-fertig-bestueckt-2021_t.jpg", type: "image" },
    { src: "/gallery/hardware-from-scratch/platine-layout-in-der-software.jpg", thumb: "/gallery/hardware-from-scratch/platine-layout-in-der-software_t.jpg", type: "image" },
    { src: "/gallery/hardware-from-scratch/platine-layout-render.jpg", thumb: "/gallery/hardware-from-scratch/platine-layout-render_t.jpg", type: "image" },
    { src: "/gallery/hardware-from-scratch/platine-smd-bestueckt.mp4", thumb: "/gallery/hardware-from-scratch/platine-smd-bestueckt_t.jpg", type: "video" },
    { src: "/gallery/hardware-from-scratch/platinen-geaetzt-bedrahtet.jpg", thumb: "/gallery/hardware-from-scratch/platinen-geaetzt-bedrahtet_t.jpg", type: "image" },
    { src: "/gallery/hardware-from-scratch/platinenfraese-kupferplatine.mp4", thumb: "/gallery/hardware-from-scratch/platinenfraese-kupferplatine_t.jpg", type: "video" },
    { src: "/gallery/hardware-from-scratch/pneumatik-handhabungsstation-01.jpg", thumb: "/gallery/hardware-from-scratch/pneumatik-handhabungsstation-01_t.jpg", type: "image" },
    { src: "/gallery/hardware-from-scratch/pneumatik-handhabungsstation-02.jpg", thumb: "/gallery/hardware-from-scratch/pneumatik-handhabungsstation-02_t.jpg", type: "image" },
    { src: "/gallery/hardware-from-scratch/pneumatik-handhabungsstation-03.jpg", thumb: "/gallery/hardware-from-scratch/pneumatik-handhabungsstation-03_t.jpg", type: "image" },
    { src: "/gallery/hardware-from-scratch/pneumatik-handhabungsstation-04.jpg", thumb: "/gallery/hardware-from-scratch/pneumatik-handhabungsstation-04_t.jpg", type: "image" },
    { src: "/gallery/hardware-from-scratch/pneumatik-handhabungsstation-05.jpg", thumb: "/gallery/hardware-from-scratch/pneumatik-handhabungsstation-05_t.jpg", type: "image" },
    { src: "/gallery/hardware-from-scratch/pneumatik-handhabungsstation-06.jpg", thumb: "/gallery/hardware-from-scratch/pneumatik-handhabungsstation-06_t.jpg", type: "image" },
    { src: "/gallery/hardware-from-scratch/pneumatik-ventilinsel-und-steuerung.jpg", thumb: "/gallery/hardware-from-scratch/pneumatik-ventilinsel-und-steuerung_t.jpg", type: "image" },
    { src: "/gallery/hardware-from-scratch/technische-zeichnung.mp4", thumb: "/gallery/hardware-from-scratch/technische-zeichnung_t.jpg", type: "video" },
  ],
  "FlexiStylus": [
    { src: "/gallery/flexistylus-salz/salz2026-01-stand-aufbau.jpg", thumb: "/gallery/flexistylus-salz/salz2026-01-stand-aufbau_t.jpg", type: "image" },
    { src: "/gallery/flexistylus-salz/salz2026-02-stylus-und-headset-am-stand.jpg", thumb: "/gallery/flexistylus-salz/salz2026-02-stylus-und-headset-am-stand_t.jpg", type: "image" },
    { src: "/gallery/flexistylus-salz/salz2026-03-stand-vor-oeffnung.jpg", thumb: "/gallery/flexistylus-salz/salz2026-03-stand-vor-oeffnung_t.jpg", type: "image" },
    { src: "/gallery/flexistylus-salz/salz2026-04-buehne.jpg", thumb: "/gallery/flexistylus-salz/salz2026-04-buehne_t.jpg", type: "image" },
    { src: "/gallery/flexistylus-salz/salz2026-05-besucherin-am-geraet.jpg", thumb: "/gallery/flexistylus-salz/salz2026-05-besucherin-am-geraet_t.jpg", type: "image" },
    { src: "/gallery/flexistylus-salz/salz2026-06-besucherin-mit-headset.jpg", thumb: "/gallery/flexistylus-salz/salz2026-06-besucherin-mit-headset_t.jpg", type: "image" },
    { src: "/gallery/flexistylus-salz/salz2026-07-besucher-am-stand.jpg", thumb: "/gallery/flexistylus-salz/salz2026-07-besucher-am-stand_t.jpg", type: "image" },
    { src: "/gallery/flexistylus-salz/salz2026-08-stylus-in-der-hand.jpg", thumb: "/gallery/flexistylus-salz/salz2026-08-stylus-in-der-hand_t.jpg", type: "image" },
    { src: "/gallery/flexistylus-salz/salz2026-09-besucher-am-laptop.jpg", thumb: "/gallery/flexistylus-salz/salz2026-09-besucher-am-laptop_t.jpg", type: "image" },
    { src: "/gallery/flexistylus-salz/salz2026-10-besucherin-mit-headset.jpg", thumb: "/gallery/flexistylus-salz/salz2026-10-besucherin-mit-headset_t.jpg", type: "image" },
    { src: "/gallery/flexistylus-salz/salz2026-11-einweisung-am-stand.jpg", thumb: "/gallery/flexistylus-salz/salz2026-11-einweisung-am-stand_t.jpg", type: "image" },
    { src: "/gallery/flexistylus-salz/salz2026-12-besucherin-am-laptop.jpg", thumb: "/gallery/flexistylus-salz/salz2026-12-besucherin-am-laptop_t.jpg", type: "image" },
    { src: "/gallery/flexistylus-salz/salz2026-13-besucher-schreibt-mit-stylus.jpg", thumb: "/gallery/flexistylus-salz/salz2026-13-besucher-schreibt-mit-stylus_t.jpg", type: "image" },
    { src: "/gallery/flexistylus-salz/salz2026-14-stand-im-betrieb.jpg", thumb: "/gallery/flexistylus-salz/salz2026-14-stand-im-betrieb_t.jpg", type: "image" },
    { src: "/gallery/flexistylus-salz/salz2026-15-einweisung-mit-headset.jpg", thumb: "/gallery/flexistylus-salz/salz2026-15-einweisung-mit-headset_t.jpg", type: "image" },
    { src: "/gallery/flexistylus-salz/salz2026-16-andrang-am-stand.jpg", thumb: "/gallery/flexistylus-salz/salz2026-16-andrang-am-stand_t.jpg", type: "image" },
    { src: "/gallery/flexistylus-salz/salz2026-flickr-album.jpg", thumb: "/gallery/flexistylus-salz/salz2026-flickr-album_t.jpg", type: "image" },
    { src: "/gallery/flexistylus-salz/salz2026-stand-team.jpg", thumb: "/gallery/flexistylus-salz/salz2026-stand-team_t.jpg", type: "image" },
  ],
  "Circuit-Crusher": [
    { src: "/gallery/circuit-crusher/lichtershow.mp4", thumb: "/gallery/circuit-crusher/lichtershow_t.jpg", type: "video" },
    { src: "/gallery/circuit-crusher/gruppenrunde-1.mp4", thumb: "/gallery/circuit-crusher/gruppenrunde-1_t.jpg", type: "video" },
    { src: "/gallery/circuit-crusher/gruppenrunde-2.mp4", thumb: "/gallery/circuit-crusher/gruppenrunde-2_t.jpg", type: "video" },
    { src: "/gallery/circuit-crusher/runde-1.mp4", thumb: "/gallery/circuit-crusher/runde-1_t.jpg", type: "video" },
    { src: "/gallery/circuit-crusher/runde-2.mp4", thumb: "/gallery/circuit-crusher/runde-2_t.jpg", type: "video" },
    { src: "/gallery/circuit-crusher/runde-3.mp4", thumb: "/gallery/circuit-crusher/runde-3_t.jpg", type: "video" },
    { src: "/gallery/circuit-crusher/bauphase-2023-12-erster-antrieb.mp4", thumb: "/gallery/circuit-crusher/bauphase-2023-12-erster-antrieb_t.jpg", type: "video" },
    { src: "/gallery/circuit-crusher/circuit-crusher-praesentation-fhtw.jpg", thumb: "/gallery/circuit-crusher/circuit-crusher-praesentation-fhtw_t.jpg", type: "image" },
    { src: "/gallery/circuit-crusher/circuit-crusher-roboter-beleuchtet.jpg", thumb: "/gallery/circuit-crusher/circuit-crusher-roboter-beleuchtet_t.jpg", type: "image" },
    { src: "/gallery/circuit-crusher/circuit-crusher-roboter-nahaufnahme.jpg", thumb: "/gallery/circuit-crusher/circuit-crusher-roboter-nahaufnahme_t.jpg", type: "image" },
    { src: "/gallery/circuit-crusher/circuit-crusher-team-auf-der-buehne.jpg", thumb: "/gallery/circuit-crusher/circuit-crusher-team-auf-der-buehne_t.jpg", type: "image" },
    { src: "/gallery/circuit-crusher/circuit-crusher-teamplakat.jpg", thumb: "/gallery/circuit-crusher/circuit-crusher-teamplakat_t.jpg", type: "image" },
    { src: "/gallery/circuit-crusher/roboringout-2024-alle-teams.jpg", thumb: "/gallery/circuit-crusher/roboringout-2024-alle-teams_t.jpg", type: "image" },
    { src: "/gallery/circuit-crusher/roboringout-2024-eroeffnung.jpg", thumb: "/gallery/circuit-crusher/roboringout-2024-eroeffnung_t.jpg", type: "image" },
    { src: "/gallery/circuit-crusher/roboringout-2024-gruppenbild-01.jpg", thumb: "/gallery/circuit-crusher/roboringout-2024-gruppenbild-01_t.jpg", type: "image" },
    { src: "/gallery/circuit-crusher/roboringout-2024-gruppenbild-02.jpg", thumb: "/gallery/circuit-crusher/roboringout-2024-gruppenbild-02_t.jpg", type: "image" },
    { src: "/gallery/circuit-crusher/roboringout-2024-gruppenbild-03.jpg", thumb: "/gallery/circuit-crusher/roboringout-2024-gruppenbild-03_t.jpg", type: "image" },
    { src: "/gallery/circuit-crusher/roboringout-2024-gruppenbild-04.jpg", thumb: "/gallery/circuit-crusher/roboringout-2024-gruppenbild-04_t.jpg", type: "image" },
    { src: "/gallery/circuit-crusher/roboringout-2024-roboter-wird-gesetzt.jpg", thumb: "/gallery/circuit-crusher/roboringout-2024-roboter-wird-gesetzt_t.jpg", type: "image" },
    { src: "/gallery/circuit-crusher/roboringout-2024-saal.jpg", thumb: "/gallery/circuit-crusher/roboringout-2024-saal_t.jpg", type: "image" },
    { src: "/gallery/circuit-crusher/roboringout-2024-team-am-ring.jpg", thumb: "/gallery/circuit-crusher/roboringout-2024-team-am-ring_t.jpg", type: "image" },
    { src: "/gallery/circuit-crusher/roboringout-2024-teams-am-tisch-01.jpg", thumb: "/gallery/circuit-crusher/roboringout-2024-teams-am-tisch-01_t.jpg", type: "image" },
    { src: "/gallery/circuit-crusher/roboringout-2024-teams-am-tisch-02.jpg", thumb: "/gallery/circuit-crusher/roboringout-2024-teams-am-tisch-02_t.jpg", type: "image" },
    { src: "/gallery/circuit-crusher/roboringout-2024-zweikampf.jpg", thumb: "/gallery/circuit-crusher/roboringout-2024-zweikampf_t.jpg", type: "image" },
  ],
  "MONUMENTAL": [
    { src: "/gallery/monumental/monumental-03-bedienung-mit-stift.jpg", thumb: "/gallery/monumental/monumental-03-bedienung-mit-stift_t.jpg", type: "image" },
    { src: "/gallery/monumental/monumental-04-bedienung-mit-gamepad.jpg", thumb: "/gallery/monumental/monumental-04-bedienung-mit-gamepad_t.jpg", type: "image" },
  ],
  "MetaMove": [
    { src: "/gallery/metamove/metamove-teleoperation-abb-gofa.mp4", thumb: "/gallery/metamove/metamove-teleoperation-abb-gofa_t.jpg", type: "video" },
    { src: "/gallery/metamove/metamove-laborzelle-mit-headset.jpg", thumb: "/gallery/metamove/metamove-laborzelle-mit-headset_t.jpg", type: "image" },
  ],
  "ABB robot cell in RobotStudio": [
    { src: "/gallery/robotstudio/robotstudio-01-zelle-gesamtansicht.mp4", thumb: "/gallery/robotstudio/robotstudio-01-zelle-gesamtansicht_t.jpg", type: "video" },
    { src: "/gallery/robotstudio/robotstudio-02-arm-nahaufnahme.mp4", thumb: "/gallery/robotstudio/robotstudio-02-arm-nahaufnahme_t.jpg", type: "video" },
  ],
  "Conveyor belt with a digital twin": [
    { src: "/gallery/foerderband/foerderband-bauphase-cad-gestell.mp4", thumb: "/gallery/foerderband/foerderband-bauphase-cad-gestell_t.jpg", type: "video" },
    { src: "/gallery/foerderband/foerderband-hmi-und-digitaler-zwilling.mp4", thumb: "/gallery/foerderband/foerderband-hmi-und-digitaler-zwilling_t.jpg", type: "video" },
  ],
  "Taurob-Tracker": [
    { src: "/gallery/taurob-tracker/taurob-projektvideo-2x.mp4", thumb: "/gallery/taurob-tracker/taurob-projektvideo-2x_t.jpg", type: "video" },
    { src: "/gallery/taurob-tracker/taurob-tracker-im-labor.jpg", thumb: "/gallery/taurob-tracker/taurob-tracker-im-labor_t.jpg", type: "image" },
  ],
  "TurtleBot 4 linear controller": [
    { src: "/gallery/turtlebot4/turtlebot4-linearregler-fahrt.mp4", thumb: "/gallery/turtlebot4/turtlebot4-linearregler-fahrt_t.jpg", type: "video" },
  ],
  "Crayler: operating an autonomous forklift": [
    { src: "/gallery/crayler/crayler-bedienung-am-tablet.mp4", thumb: "/gallery/crayler/crayler-bedienung-am-tablet_t.jpg", type: "video" },
    { src: "/gallery/crayler/crayler-bedienung-vor-ort.jpg", thumb: "/gallery/crayler/crayler-bedienung-vor-ort_t.jpg", type: "image" },
    { src: "/gallery/crayler/crayler-stand-mit-kran.jpg", thumb: "/gallery/crayler/crayler-stand-mit-kran_t.jpg", type: "image" },
  ],
};
